package sn.gestion.clinique.metier;

import java.util.List;

import sn.gestion.clinique.entites.*;

public interface IMedecinMetier {
	public Message envoyerMessage(Message message);
	public List<Users> listeUser(int id);
	public List<Message> listeMessages(int exp,int des);
	public List<Users> verifCompte(String login,String question,String reponse);
	public void SupprimerCertificat(int idCert);
	public List<Rdv> ListRdvMed(int idMed);
	public List<Patient> searchPatient(String string,int idMed);
	public List<Rdv> searchRdv(String string,int idMed);
	public List<Patient> ListPatient(int idMed);
	public void ModifierBilan(Bilan bilan);
	public List<Bilan> ListBilan(int idPat);
	public Bilan ajouterBilan(Bilan bilan);
	public Medecin chercherMedecin(int idmedecin);
	public List<Patient> ListPatientSecr(int idsecr);
	public List<Specialite> ListSpecialite();
	public Certificat getCertificat(int idCert);
	public void SupprimerAntecedant(int ant);
	public void SupprimerBilan(int idBilan);
	public void SupprimerVisite(int idvisite);
	public Administrateur ajouterAdministrateur(Administrateur admin);
	public Antecedant ajouterAntecedant(Antecedant ant);
	public void ModifierAdministrateur(Administrateur admin);
	public List<Paiement> ListPaiement();
	public Patient getPatient(String name);
	public Dossier AjouterDossier(Dossier dossier);
	public Dossier ChercherDossier(int iddossier);
	public void ModifierDossier(Dossier d);
	public void ModifierAntecdant(Antecedant ant);
	public void ModifierPatient(Patient patient);
	public void ModifierOrdonnance(Ordonnance o);
	public List<Certificat> listCertificat(int idpatient);
	public Antecedant getAntecedant(int idAnt);
	public Bilan getBilan(int idBilan);
	public List<Users> VerifUsers();
	public void ModifierMedecin(Medecin medecin);
	void SupprimerRdv(int idrdv);
	Rdv ChercherRdv(int idrdv);
	public Ordonnance getOrdonnance(int idord);
	public void SupprimerOrdonnance(int idOrd);
	List<Patient> chercherPatient(String nom);
	List<Ordonnance> ListOrdonnance();
	List<Ordonnance> ListOrdonnance(int idpatient);
	public List<Antecedant> listAntecedants(int idpatient);
	public Visite getVisite(int idVisite);
	public Secretaire chercherSecretaire(int id);
	public List<Service> ListService();
	public List<Rdv> ListRdv();
	public List<Patient> getPatient();
	public List<Visite> ListVisite(int idPat);
	public List<Rdv> ListRdv(int idPat);
	public Patient getPatient(int idPat);
	public void ModifierRdv(Rdv rdv);
	public Rdv AjouterRdv(Rdv rdv);
	public Patient AjouterPatient(Patient pat);
	public void ModifierVisite(Visite visite);
	public void ModifierPaiement(Paiement paiement);
	public Paiement AjouterPaiement(Paiement paiement);
	public Visite AjouterVisite(Visite visite);
	public void ajouterOrdonnance(Ordonnance ord);
	public Certificat AjouterCertificat(Certificat cert);
	public void ModifierCertificat(Certificat certificat);
	public List<Rdv> ListRdvpat(String name);
	public List<Secretaire> chercherSecretaire(String chaine);
	public List<Medecin> chercherMedecin(String chaine);
	public int notifMessage(int exp);
}
