package sn.gestion.clinique.dao;

import java.util.List;

import javax.persistence.Query;

import sn.gestion.clinique.entites.*;

public interface ICliniqueDao {
	public Users getUser(int id);
	public int notifMessage(int id);
	public List<Administrateur> ListAdministrateur();
	public List<Users> verifCompte(String login,String question,String reponse);
	public Administrateur getAdministrateur(int idAdmin);
	public Certificat getCertificat(int idCert);
	public Patient getPatient(int idpatient);
	public Medecin getMedecin(int idmedecin);
	public Visite getVisite(int idvisite);
	public List<Antecedant> listAntecedants(int idpatient);
	public List<Patient> ListPatient();
	public List<Patient> ListPatientSecr(int idsecr);
	public List<Service> ListService();
	public List<Specialite> ListSpecialite();
	public List<Patient> ListPatient(String nompatient);
	public List<Patient> ListPatient(int idMed);
	public List<Medecin> ListMedecin();
	public List<Paiement> ListPaiement();
	public Antecedant getAntecedant(int idAnt);
	public Bilan getBilan(int idBilan);
	public Ordonnance getOrdonnance(int idord);
	public List<Certificat> listCertificat(int idpatient);
	public List<Rdv> ListRdv();
	public List<Rdv> ListRdvMed(int idMed);
	public List<Rdv> ListRdv(String date);
	public List<Rdv> ListRdv(int idpatient);
	public List<Rdv> ListRdvpat(String name);
	public List<Visite> ListVisite(int idpatient);
	public List<Dossier> ListDossier();
	public List<Dossier> ListDossier(int idmedecin);
	public List<Rdv> ListRdvMedecin(Medecin medecin, String jour);
	public Rdv ChercherRdv(int idrdv);
	public Rdv AjouterRdv(Rdv rdv);
	public void SupprimerRdv(int idrdv);
	public Users AjouterMedecin(Users user);
	public Users AjouterInfirmier(Users user);
	public Users AjouterSecretaire(Users user);
	public Bilan AjouterBilan(Bilan bilan);
	public void SupprimerSecretaire(int idsecretaire);
	public void SupprimerBilan(int idBilan);
	
	public void SupprimerVisite(int idvisite);
	public void SupprimerMedecin(int idmedecin);
	public void SupprimerAntecedant(int ant);
	public Paiement AjouterPaiement(Paiement paiement);
	public Visite AjouterVisite(Visite visite);
	public Dossier AjouterDossier(Dossier dossier);
	public Patient AjouterPatient(Patient patient);
	public Ordonnance AjouterOrdonnance(Ordonnance ordonnance);
	public Dossier ChercherDossier(int iddossier);
	public List<Patient> ChercherPatient(String string);
	public List<Patient> searchPatient(String string,int idMed);
	public List<Rdv> searchRdv(String string,int idMed);
	public void ModifierDossier(Dossier dossier);
	public Administrateur ajouterAdministrateur(Administrateur admin);
	public Antecedant ajouterAntecdant(Antecedant ant);
	public void ModifierAdministrateur(Administrateur admin);
	public void ModifierBilan(Bilan bilan);
	public List<Bilan> ListBilan(int idPat);

	public void Modifiernfirmier(Infirmier infirmier);
	public void ModifierAntecedant(Antecedant ant);
	public void ModifierMedecin(Medecin medecin);
	public void ModifierPatient(Patient patient);
	public void ModifierSecretaire(Secretaire secretaire);
	public void ModifierOrdonnance(Ordonnance o);
	public Medecin chercherMedecin(int idmedecin);
	public Infirmier chercherInfirmier(int idinfimier);
	public Secretaire chercherSecretaire(int idsecretaire);
	public List<Secretaire> chercherSecretaire(String chaine);
	public List<Medecin> chercherMedecin(String chaine);
	public void ModifierPaiement(Paiement paiement);
	public void AnnulerRdv(Long id);
	public void AffecterPatient(int idpatient, int idmedecin);
	public void ModifierInformationPatient(Patient p);
	public void ModifierVisite(Visite v);
	public void ModifierRdv(Rdv rdv);
	List<Infirmier> ListInfirmier();
	List<Secretaire> ListSecretaire();
	List<Users> VerifUsers();
	List<Ordonnance> ListOrdonnance();
	List<Ordonnance> ListOrdonnance(int idpatient);
	public void SupprimerOrdonnance(int idOrd);
	public void SupprimerCertificat(int idCert);
	public Certificat AjouterCertificat(Certificat cert);
	public void ModifierCertificat(Certificat certificat);
	public void SupprimerAdministrateur(int idAdmin);
	public Message envoyerMessage(Message message);
	public List<Users> listeUser(int id);
	public List<Message> listeMessages(int exp,int des);
}
